### ISSUE TITLE
Proof-reading pages

### ISSUE THREAD

**Issue by AlexikM** [CondensationDS/Condensation-Website#24]
Keep the language tone as simple as possible - inform @AlexikM for review

**Tasks:**

- [x] Landing page
- [x] What is Condensation ?
- [ ] Case Studies 
- [ ] Develop with Condensation
- [ ] Meet the Team
- [ ] Make it happen
